# Site settings
title: UA / INTERNSHIPS
unicode_title: UA üöÄ INTERNSHIS
description: >
  –î–æ–ø–æ–º–∞–≥–∞—î–º–æ —É–∫—Ä–∞—ó–Ω—Å—å–∫–∏–º —Å—Ç—É–¥–µ–Ω—Ç–∞–º –≤–ª–∞—à—Ç—É–≤–∞—Ç–∏—Å—è –Ω–∞ —Å—Ç–∞–∂—É–≤–∞–Ω–Ω—è –≤ —Ç–æ–ø–æ–≤–∏—Ö —Ç–µ—Ö–Ω–æ–ª–æ–≥—ñ—á–Ω–∏—Ö –∫–æ–º–ø–∞–Ω—ñ—è—Ö –ö—Ä–µ–º–Ω—ñ—î–≤–æ—ó –î–æ–ª–∏–Ω–∏.

baseurl: ""
url: "http://hitchhiker.ma" # the base hostname & protocol for your site

twitter: uainternships
# disqus: your_disqus_forum_shortname

# google_analytics: 'UA-XXXXXXXX-X'

# Syntax highlighting
highlightstyle: ''
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude:
  - "README.md"
  - "README.html"

# Build settings
highlighter: null
markdown: kramdown
